required = [
    "github.com/emicklei/go-restful",
    "github.com/onsi/ginkgo", # for test framework
    "github.com/onsi/gomega", # for test matchers
    "k8s.io/client-go/plugin/pkg/client/auth/gcp", # for development against gcp
    "k8s.io/code-generator/cmd/client-gen", # for go generate
    "k8s.io/code-generator/cmd/deepcopy-gen", # for go generate
    "k8s.io/kube-openapi/cmd/openapi-gen", # for go generate
    "sigs.k8s.io/controller-tools/cmd/controller-gen", # for crd/rbac generation
    "sigs.k8s.io/controller-runtime/pkg/client/config",
    "sigs.k8s.io/controller-runtime/pkg/controller",
    "sigs.k8s.io/controller-runtime/pkg/handler",
    "sigs.k8s.io/controller-runtime/pkg/manager",
    "sigs.k8s.io/controller-runtime/pkg/runtime/signals",
    "sigs.k8s.io/controller-runtime/pkg/source",
    "sigs.k8s.io/testing_frameworks/integration", # for integration testing
    "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1",
    "github.com/tensorflow/tensorflow/tensorflow/go", # for tensorflow protos,
    "github.com/spf13/cobra"
    ]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
  name = "k8s.io/code-generator"
  non-go = false
  unused-packages = false

[[prune.project]]
  name = "k8s.io/gengo"
  unused-packages = false

[[prune.project]]
  name = "github.com/tensorflow/tensorflow"
  unused-packages = false
  non-go = false

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
name = "gopkg.in/fsnotify.v1"
source = "https://github.com/fsnotify/fsnotify.git"
version="v1.4.7"

[[constraint]]
  name = "knative.dev/serving"
  version = "=v0.11"

[[override]]
  name="sigs.k8s.io/controller-runtime"
  version = "=v0.3.0"

[[override]]
  name = "knative.dev/pkg"
  branch = "release-0.11"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.18.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.18.2"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.18.2"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.18.2"

[[constraint]]
  name = "k8s.io/kube-openapi"
  # This is the version at which k8s.io/apiserver depends on this at its 1.18 tag.
  revision = "bf4fb3bd569c8c84504d856598edbc66c10d8744"

[[override]]
  name = "github.com/tensorflow/tensorflow"
  version = "=v1.13.1"

[[constraint]]
  name = "github.com/google/go-cmp"
  revision = "6f77996f0c42f7b84e5a2b252227263f93432e9b"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "=1.18.2"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.18.2"

[[override]]
  name = "k8s.io/klog"
  version = "v2.0.0"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.18.2"

[[constraint]]
  name = "k8s.io/utils"
  # This is the version at which k8s.io/client-go depends on this at its 1.18 tag.
  revision = "a9aa75ae1b89e1b992c33383f48e942d97e52dae"

[[constraint]]
  name = "k8s.io/gengo"
  revision = "793b05dca9b871fdc15aeaff1f201e141ef5afa7"
